version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
    secrets:
      - password
      - root_password
      - user
      - root_user
      - db_name
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    networks:
      inception:
    secrets:
      - password
      - root_password
      - user
      - root_user
      - db_name

networks:
  inception:

secrets:
  password:
    file: ../secrets/password
  root_password:
    file: ../secrets/root_password
  user:
    file: ../secrets/user
  root_user:
    file: ../secrets/root_user
  db_name:
    file: ../secrets/db_name
