version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
      - ~/nginx_ssl:/etc/nginx/ssl:ro
    networks:
      inception:
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress-php
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - ./database:/var/lib/mysql
    networks:
      inception:


networks:
  inception:
